[connections.snowflake]
account = "fy50488.central-us.azure"
user = "github_actions_user"
private_key = "${{ secrets.SF_PRIVATE_KEY }}"
role = "github_actions_user"
warehouse = "PUBLIC_WH"
database = "BIGIRON_WAREHOUSE"
schema= "PUBLIC_DEV"
