[connections.snowflake]
account = "${{ secrets.SF_ACCOUNT }}"
user = "${{ secrets.SF_USERNAME }}"
private_key = "${{ secrets.SF_PRIVATE_KEY }}"
role = "${{ secrets.SF_ROLE }}"
warehouse = "${{ secrets.SF_WAREHOUSE }}"
database = "${{ secrets.SF_DATABASE }}"
