config-version: 1

# Ruta a los scripts de cambios en Snowflake
root-folder: deploy

# Ruta a los módulos (si los tienes, si no, deja null)
modules-folder: null

# Ruta al archivo connections.toml
connections-file-path: connections.toml

# Nombre de la conexión definida en connections.toml
connection-name: my_snowflake

# Nombre de la tabla de historial de cambios
change-history-table: BIGIRON_WAREHOUSE.PUBLIC_DEV.CHANGE_HISTORY

# Activa la creación de la tabla de historial si no existe
create-change-history-table: true

# Habilita el modo detallado
verbose: true
