name: Deploy Snowflake Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange
        run: |
          schemachange -f $GITHUB_WORKSPACE/migrations --create-change-history-table
        env:
          SF_ACCOUNT: "fy50488.central-us.azure"
          SF_USERNAME: "github_actions_user"
          SF_PASSWORD: ':3&a493vOqvtxQE8'  
          SF_ROLE: "DATA_TEAM"
          SF_WAREHOUSE: "PUBLIC_WH"
          SF_DATABASE: "BIGIRON_WAREHOUSE"
          SF_SCHEMA: "PUBLIC_DEV"
