name: Deploy Snowflake Schema Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install schemachange snowflake-connector-python

      - name: Create Snowflake connection config
        run: |
          cat <<EOF > connections.toml
          [connections.my_snowflake]
          account = "tu_cuenta_snowflake"
          user = "TU_USUARIO"
          private_key_path = "snowflake_rsa_key.p8"
          role = "TU_ROLE"
          warehouse = "TU_WAREHOUSE"
          database = "TU_DATABASE"
          schema = "TU_SCHEMA"
          EOF
          chmod 600 connections.toml

      - name: Save Snowflake Private Key
        run: |
          cat <<EOF > snowflake_rsa_key.p8
          -----BEGIN ENCRYPTED PRIVATE KEY-----
          MIIFJDBWBgkqhkiG9w0BBQ0wSTAxBgkqhkiG9w0BBQwwJAQQcFGnXAxwJLOA5F+F
          4XnS8AICCAAwDAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQIxZMwHVsjOcoEggTI
          ...
          9WeLYjGUGnmhBk5mCn2VPP59X1Bzwu0m5RywwBbTcbObNmegCXfg97bvupqqjgUZ
          LBL/XVg18BpwN7KDAbCXXgjlNqDVYNa7BSTVI3/2+dP6W2SR/21r1NlyWRGFwAdI
          fo/xZ6SA7SohEbUYPYeL44yLAkIoIpKdiOOD6nrbdCxvCn3b881qexKElUr9AHXA
          cnijDw4IjvWW5n8b8xHXr3W4upQv/sDnLL/gYp0PEhiG0CbyXl9cFeYW8xWER6ig
          +9pjRPWvpIR5CZojooSKNtH6JD+0deXZ
          -----END ENCRYPTED PRIVATE KEY-----
          EOF
          chmod 600 snowflake_rsa_key.p8

      - name: Deploy schema changes with schemachange
        run: |
          schemachange deploy \
            --connections-file-path "connections.toml" \
            --connection-name my_snowflake \
            -f "." \
            --create-change-history-table
