name: Deploy Schema to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install schemachange snowflake-connector-python

      - name: Crear clave privada en el runner
        run: |
          cat <<EOF > snowflake_rsa_key.p8
          -----BEGIN RSA PRIVATE KEY-----
          TU_CLAVE_PRIVADA_AQUÍ
          -----END RSA PRIVATE KEY-----
          EOF
          chmod 600 snowflake_rsa_key.p8
        shell: bash

      - name: Crear clave pública en el runner
        run: |
          cat <<EOF > snowflake_rsa_key.pub
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5h97aL0Ehzy1k10S0O+X
          yagrblvCIN6inp7JwexuT7lhIXjR8vYMFa5xitJa/ygY89xei/Kp60CYun5YK+64
          cNpwa90bEVHG3rryVgmk35CxOcAUxPyBOf08RHDYJrjRowJ+UfhDvvXmtqin/Ehw
          gYkIuOCLawMcZxqCV1+UPtecO19TBVbYqg1EKhABS0qwCVyzwlTgYTISzs10fxuM
          QL7cbDlEzXSrgy7l6E3NcqLAzlmu4HiXWvesQ6g1GKjytC+3b0MtRWOGKjkfngK0
          tFISQFJnc6AdBWXeLJb6rQubdhWBMZjb5SRaIszxYvZhdEy9WWbCWQBv/e5qgsbg
          KwIDAQAB
          -----END PUBLIC KEY-----
          EOF
        shell: bash

      - name: Crear archivo de conexión
        run: |
          cat <<EOF > connections.toml
          [connections]
          account = "fy50488.central-us.azure"
          user = "github_actions_user"
          private_key_path = "snowflake_rsa_key.p8"
          role = "DATA_TEAM"
          warehouse = "PUBLIC_WH"
          database = "BIGIRON_WAREHOUSE"
          schema = "PUBLIC_DEV"
          EOF
        shell: bash

      - name: Ejecutar schemachange
        run: |
          schemachange --connections-file-path "connections.toml" \
            --connection-name connections \
            --private-key-path "snowflake_rsa_key.p8" \
            -f "." \
            --create-change-history-table
        shell: bash
