name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.8.x'

      - name: Create connections.toml
        run: |
          # Write each line of the TOML via echo statements
          echo "[my_snowflake]"                                  >  connections.toml
          echo "account = \"fy50488.central-us.azure\""          >> connections.toml
          echo "user = \"github_actions_user\""                  >> connections.toml
          echo "role = \"GITHUB_ACTIONS_ROLE\""                            >> connections.toml
          echo "warehouse = \"PUBLIC_WH\""                       >> connections.toml
          echo "database = \"BIGIRON_WAREHOUSE\""                >> connections.toml
          echo "schema = \"PUBLIC_DEV\""                         >> connections.toml
          echo 'private_key = """'                               >> connections.toml
          echo "${{ secrets.SF_PRIVATE_KEY }}"                   >> connections.toml
          echo '"""'                                             >> connections.toml

      - name: Install schemachange
        run: pip install schemachange

      - name: Check existing change history table
        run: |
          schemachange deploy \
            --connections-file-path "$GITHUB_WORKSPACE/connections.toml" \
            --connection-name my_snowflake \
            --change-history-table BIGIRON_WAREHOUSE.PUBLIC_DEV.CHANGE_HISTORY \
            --verbose

      - name: Debug schemachange
        run: |
          schemachange deploy --dry-run --verbose
     
      - name: Run schemachange deploy
        run: |
          schemachange deploy \
            --config-folder "$GITHUB_WORKSPACE" \
            --config-file-name "schemachange-config.yml"


