name: Deploy Snowflake Schema Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install schemachange snowflake-connector-python

      - name: Save Snowflake Private Key
        run: |
          echo "Guardando clave privada..."
          cat <<EOF > snowflake_rsa_key.p8
          -----BEGIN ENCRYPTED PRIVATE KEY-----
          MIIFJDBWBgkqhkiG9w0BBQ0wSTAxBgkqhkiG9w0BBQwwJAQQcFGnXAxwJLOA5F+F
          4XnS8AICCAAwDAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQIxZMwHVsjOcoEggTI
          ...
          9WeLYjGUGnmhBk5mCn2VPP59X1Bzwu0m5RywwBbTcbObNmegCXfg97bvupqqjgUZ
          LBL/XVg18BpwN7KDAbCXXgjlNqDVYNa7BSTVI3/2+dP6W2SR/21r1NlyWRGFwAdI
          fo/xZ6SA7SohEbUYPYeL44yLAkIoIpKdiOOD6nrbdCxvCn3b881qexKElUr9AHXA
          cnijDw4IjvWW5n8b8xHXr3W4upQv/sDnLL/gYp0PEhiG0CbyXl9cFeYW8xWER6ig
          +9pjRPWvpIR5CZojooSKNtH6JD+0deXZ
          -----END ENCRYPTED PRIVATE KEY-----
          EOF

          chmod 600 snowflake_rsa_key.p8
          ls -l snowflake_rsa_key.p8  # Verifica que el archivo existe y tiene permisos correctos
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=${GITHUB_WORKSPACE}/snowflake_rsa_key.p8" >> $GITHUB_ENV

      - name: Fix permissions on connections.toml
        run: |
          chmod 600 connections.toml
          ls -l connections.toml  # Verifica que el archivo tiene los permisos correctos

      - name: Deploy schema changes with schemachange
        run: |
          schemachange deploy \
            --connections-file-path "$GITHUB_WORKSPACE/connections.toml" \
            --connection-name my_snowflake \
            -f "$GITHUB_WORKSPACE/migrations" \
            --create-change-history-table
