name: Deploy Snowflake Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Verificar Secrets en GitHub Actions
        run: |
          echo "🔍 Verificando secretos..."
          echo "SF_USERNAME=$(if [ -z "${{ secrets.SF_USERNAME }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_PASSWORD=$(if [ -z "${{ secrets.SF_PASSWORD }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_ACCOUNT=$(if [ -z "${{ secrets.SF_ACCOUNT }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_DATABASE=$(if [ -z "${{ secrets.SF_DATABASE }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_ROLE=$(if [ -z "${{ secrets.SF_ROLE }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_SCHEMA=$(if [ -z "${{ secrets.SF_SCHEMA }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
          echo "SF_WAREHOUSE=$(if [ -z "${{ secrets.SF_WAREHOUSE }}" ]; then echo '❌ VACÍO'; else echo '✅ OK'; fi)"
        shell: bash

      - name: Verificar que SF_USERNAME no esté vacío
        run: |
          if [ -z "${{ secrets.SF_USERNAME }}" ]; then
            echo "❌ ERROR: SF_USERNAME está vacío. Revisa los secrets en GitHub."
            exit 1
          else
            echo "✅ SF_USERNAME está definido correctamente."
          fi

      - name: Run schemachange
        run: |
          schemachange -f $GITHUB_WORKSPACE/migrations --create-change-history-table
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
