name: Deploy to Snowflake using schemachange

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml
        run: |
          echo "[connections.snowflake]" > connections.toml
          echo "account = \"${{ secrets.SF_ACCOUNT }}\"" >> connections.toml
          echo "user = \"${{ secrets.SF_USERNAME }}\"" >> connections.toml
          echo "password = \"${{ secrets.SF_PASSWORD }}\"" >> connections.toml
          echo "role = \"${{ secrets.SF_ROLE }}\"" >> connections.toml
          echo "warehouse = \"${{ secrets.SF_WAREHOUSE }}\"" >> connections.toml
          echo "database = \"${{ secrets.SF_DATABASE }}\"" >> connections.toml
          echo "schema = \"${{ secrets.SF_SCHEMA }}\"" >> connections.toml

      - name: Run schemachange
        run: |
          schemachange -f $GITHUB_WORKSPACE/migrations --create-change-history-table
