name: Deploy to Snowflake

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: |
          pip install schemachange

      - name: Debug Environment Variables
        run: |
          echo "SF_USERNAME=${{ secrets.SF_USERNAME }}"
          echo "SF_ACCOUNT=${{ secrets.SF_ACCOUNT }}"

      - name: Run schemachange
        run: |
          schemachange deploy -f deploy -c connections.toml -a ${{ secrets.SF_ACCOUNT }} -u ${{ secrets.SF_USERNAME }} -r ${{ secrets.SF_ROLE }} -w ${{ secrets.SF_WAREHOUSE }} -d ${{ secrets.SF_DATABASE }}
