name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables..."
          env | grep SF_

      - name: Set and Export Snowflake Credentials
        run: |
          export SF_ACCOUNT="fy50488.central-us.azure"
          export SF_USERNAME="github_actions_user"
          export SF_PASSWORD=":3&a493vOqvtxQE8"
          export SF_ROLE="DATA_TEAM"
          export SF_WAREHOUSE="PUBLIC_WH"
          export SF_DATABASE="BIGIRON_WAREHOUSE"
          export SF_SCHEMA="PUBLIC_DEV"

          echo "Verifying exported variables..."
          env | grep SF_

      - name: Run schemachange
        run: |
          schemachange -f $GITHUB_WORKSPACE/migrations --create-change-history-table \
            --account fy50488.central-us.azure \
            --user github_actions_user \
            --password ':3&a493vOqvtxQE8' \
            --role DATA_TEAM \
            --warehouse PUBLIC_WH \
            --database BIGIRON_WAREHOUSE \
            --schema PUBLIC_DEV
