name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install schemachange snowflake-connector-python

      - name: Debug environment variables
        run: |
          echo "SF_USERNAME=${{ secrets.SF_USERNAME }}"
          echo "SF_ACCOUNT=${{ secrets.SF_ACCOUNT }}"
          echo "SF_ROLE=${{ secrets.SF_ROLE }}"
          echo "SF_DATABASE=${{ secrets.SF_DATABASE }}"
          echo "SF_SCHEMA=${{ secrets.SF_SCHEMA }}"
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

      - name: Create connections.toml
        run: |
          set -x
          echo "[connections.snowflake]" > connections.toml
          echo "account = \"${{ secrets.SF_ACCOUNT }}\"" >> connections.toml
          echo "user = \"${{ secrets.SF_USERNAME }}\"" >> connections.toml
          echo "password = \"${{ secrets.SF_PASSWORD }}\"" >> connections.toml
          echo "role = \"${{ secrets.SF_ROLE }}\"" >> connections.toml
          echo "warehouse = \"${{ secrets.SF_WAREHOUSE }}\"" >> connections.toml
          echo "database = \"${{ secrets.SF_DATABASE }}\"" >> connections.toml
          echo "schema = \"${{ secrets.SF_SCHEMA }}\"" >> connections.toml

      - name: Run schemachange
        run: |
          set -x
          schemachange -f $GITHUB_WORKSPACE/migrations --create-change-history-table
